name: CI

on:
  push:
    branches:
      - master

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - uses: peaceiris/actions-hugo@v2.4.5
      with:
        hugo-version: 0.58.0
        extended: true
    - run: |
        npm run runner
        echo "Hello foo" > public/foo.txt
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: release
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.FOO_TOKEN }}
